supportedArchitectures: {
    cpu: [
        "current",
        "x64",
        "ia32",
        "arm64",
    ],
    os: [
        "current",
        "darwin",
        "linux",
        "win32",
    ],
    libc: [
        "current",
        "glibc",
        "musl",
    ],
}